import type { ArchitectureNodeKind } from "@arch-draw/domain";

const iconLabels: Partial<Record<ArchitectureNodeKind, string>> = {
  "api-gateway": "API",
  "block-storage": "VOL",
  cache: "CAC",
  cdn: "CDN",
  "cloud-provider": "CLD",
  "cloud-region": "REG",
  "cloud-vpc": "VPC",
  compute: "CPU",
  container: "CTR",
  database: "DB",
  external: "EXT",
  firewall: "FW",
  identity: "ID",
  kubernetes: "K8S",
  "load-balancer": "LB",
  logging: "LOG",
  mermaid: "MMD",
  monitoring: "MON",
  "object-storage": "OBJ",
  queue: "Q",
  secrets: "KEY",
  service: "SVC",
  serverless: "FN",
  subnet: "SUB",
  system: "SYS",
  "group-container": "BOX",
  "aws-account": "AWS",
  "aws-region": "REG",
  "aws-availability-zone": "AZ",
  "aws-vpc": "VPC",
  "aws-subnet": "SUB",
  "aws-internet-gateway": "IGW",
  "aws-nat-gateway": "NAT",
  "aws-route-table": "RT",
  "aws-route53": "R53",
  "aws-cloudfront": "CF",
  "aws-api-gateway": "API",
  "aws-alb": "ALB",
  "aws-nlb": "NLB",
  "aws-ec2": "EC2",
  "aws-auto-scaling": "ASG",
  "aws-lambda": "LMB",
  "aws-ecs": "ECS",
  "aws-eks": "EKS",
  "aws-fargate": "FGT",
  "aws-ecr": "ECR",
  "aws-s3": "S3",
  "aws-ebs": "EBS",
  "aws-efs": "EFS",
  "aws-rds": "RDS",
  "aws-aurora": "AUR",
  "aws-dynamodb": "DDB",
  "aws-elasticache": "EC",
  "aws-redshift": "RS",
  "aws-opensearch": "OS",
  "aws-sqs": "SQS",
  "aws-sns": "SNS",
  "aws-eventbridge": "EVB",
  "aws-kinesis": "KIN",
  "aws-step-functions": "SFN",
  "aws-iam": "IAM",
  "aws-cognito": "COG",
  "aws-secrets-manager": "SEC",
  "aws-kms": "KMS",
  "aws-cloudwatch": "CW",
  "aws-cloudtrail": "CT",
  "aws-waf": "WAF",
  "aws-shield": "SHD",
  "aws-security-group": "SG",
  "code-repository": "GIT",
  "code-workspace": "WS",
  "code-package": "PKG",
  "code-module": "MOD",
  "code-folder": "DIR",
  "code-file": "FILE",
  "code-class": "CLS",
  "code-interface": "IF",
  "code-function": "FN",
  "code-method": "M",
  "code-variable": "VAR",
  "code-enum": "ENUM",
  "code-type": "TYPE",
  "code-component": "CMP",
  "code-hook": "HOOK",
  "code-middleware": "MID",
  "code-controller": "CTRL",
  "code-use-case": "UC",
  "code-entity": "ENT",
  "code-value-object": "VO",
  "code-port": "PORT",
  "code-adapter": "ADP",
  "code-schema": "SCH",
  "code-pipeline": "PIPE",
  "flow-start": "GO",
  "flow-end": "END",
  "flow-process": "PRC",
  "flow-input": "IN",
  "flow-output": "OUT",
  "flow-decision": "?",
  "flow-loop": "LOOP",
  "flow-subroutine": "SUB",
  "flow-data": "DATA",
  "flow-document": "DOC",
  algorithm: "ALG",
  "algorithm-condition": "IF",
  "algorithm-loop": "LOOP",
  "algorithm-recursion": "REC",
  "algorithm-sort": "SORT",
  "algorithm-search": "FIND",
  "algorithm-graph": "GRF",
  "algorithm-tree": "TREE",
  "algorithm-hash-table": "HASH",
  "algorithm-stack": "STK",
  "algorithm-queue": "Q",
  "algorithm-linked-list": "LIST"
};

const iconClasses: Partial<Record<ArchitectureNodeKind, string>> = {
  "api-gateway": "fa-solid fa-network-wired",
  "block-storage": "fa-solid fa-hard-drive",
  cache: "fa-solid fa-memory",
  cdn: "fa-solid fa-globe",
  "cloud-provider": "fa-solid fa-cloud",
  "cloud-region": "fa-solid fa-map-location-dot",
  "cloud-vpc": "fa-solid fa-diagram-project",
  compute: "fa-solid fa-microchip",
  container: "fa-solid fa-box",
  database: "fa-solid fa-database",
  external: "fa-solid fa-arrow-up-right-from-square",
  firewall: "fa-solid fa-shield-halved",
  identity: "fa-solid fa-user-shield",
  kubernetes: "fa-solid fa-dharmachakra",
  "load-balancer": "fa-solid fa-scale-balanced",
  logging: "fa-solid fa-file-lines",
  mermaid: "fa-solid fa-diagram-project",
  monitoring: "fa-solid fa-chart-line",
  "object-storage": "fa-solid fa-box-archive",
  queue: "fa-solid fa-list-check",
  secrets: "fa-solid fa-key",
  service: "fa-solid fa-gears",
  serverless: "fa-solid fa-bolt",
  subnet: "fa-solid fa-network-wired",
  system: "fa-solid fa-cubes",
  "group-container": "fa-solid fa-layer-group",
  "aws-account": "fa-brands fa-aws",
  "aws-region": "fa-solid fa-map",
  "aws-availability-zone": "fa-solid fa-location-dot",
  "aws-vpc": "fa-solid fa-diagram-project",
  "aws-subnet": "fa-solid fa-code-branch",
  "aws-internet-gateway": "fa-solid fa-earth-americas",
  "aws-nat-gateway": "fa-solid fa-right-left",
  "aws-route-table": "fa-solid fa-route",
  "aws-route53": "fa-solid fa-compass-drafting",
  "aws-cloudfront": "fa-solid fa-cloud",
  "aws-api-gateway": "fa-solid fa-network-wired",
  "aws-alb": "fa-solid fa-scale-balanced",
  "aws-nlb": "fa-solid fa-shuffle",
  "aws-ec2": "fa-solid fa-server",
  "aws-auto-scaling": "fa-solid fa-up-down-left-right",
  "aws-lambda": "fa-solid fa-bolt",
  "aws-ecs": "fa-solid fa-boxes-stacked",
  "aws-eks": "fa-solid fa-dharmachakra",
  "aws-fargate": "fa-solid fa-cubes-stacked",
  "aws-ecr": "fa-solid fa-box-open",
  "aws-s3": "fa-solid fa-cube",
  "aws-ebs": "fa-solid fa-hard-drive",
  "aws-efs": "fa-solid fa-folder-tree",
  "aws-rds": "fa-solid fa-database",
  "aws-aurora": "fa-solid fa-database",
  "aws-dynamodb": "fa-solid fa-table-cells-large",
  "aws-elasticache": "fa-solid fa-memory",
  "aws-redshift": "fa-solid fa-chart-column",
  "aws-opensearch": "fa-solid fa-magnifying-glass",
  "aws-sqs": "fa-solid fa-list-ol",
  "aws-sns": "fa-solid fa-bullhorn",
  "aws-eventbridge": "fa-solid fa-code-branch",
  "aws-kinesis": "fa-solid fa-wave-square",
  "aws-step-functions": "fa-solid fa-timeline",
  "aws-iam": "fa-solid fa-id-card-clip",
  "aws-cognito": "fa-solid fa-user-check",
  "aws-secrets-manager": "fa-solid fa-lock",
  "aws-kms": "fa-solid fa-key",
  "aws-cloudwatch": "fa-solid fa-clock",
  "aws-cloudtrail": "fa-solid fa-shoe-prints",
  "aws-waf": "fa-solid fa-shield-halved",
  "aws-shield": "fa-solid fa-shield",
  "aws-security-group": "fa-solid fa-user-lock",
  "code-repository": "fa-brands fa-git-alt",
  "code-workspace": "fa-solid fa-laptop-code",
  "code-package": "fa-solid fa-box",
  "code-module": "fa-solid fa-cubes",
  "code-folder": "fa-solid fa-folder",
  "code-file": "fa-solid fa-file-code",
  "code-class": "fa-solid fa-shapes",
  "code-interface": "fa-solid fa-plug",
  "code-function": "fa-solid fa-code",
  "code-method": "fa-solid fa-code",
  "code-variable": "fa-solid fa-code",
  "code-enum": "fa-solid fa-list",
  "code-type": "fa-solid fa-tag",
  "code-component": "fa-solid fa-puzzle-piece",
  "code-hook": "fa-solid fa-link",
  "code-middleware": "fa-solid fa-filter",
  "code-controller": "fa-solid fa-sliders",
  "code-use-case": "fa-solid fa-bullseye",
  "code-entity": "fa-solid fa-cube",
  "code-value-object": "fa-solid fa-gem",
  "code-port": "fa-solid fa-plug",
  "code-adapter": "fa-solid fa-plug",
  "code-schema": "fa-solid fa-sitemap",
  "code-pipeline": "fa-solid fa-code-branch",
  "flow-start": "fa-solid fa-circle-play",
  "flow-end": "fa-solid fa-circle-stop",
  "flow-process": "fa-solid fa-gears",
  "flow-input": "fa-solid fa-arrow-right-to-bracket",
  "flow-output": "fa-solid fa-arrow-right-from-bracket",
  "flow-decision": "fa-solid fa-diamond",
  "flow-loop": "fa-solid fa-rotate",
  "flow-subroutine": "fa-solid fa-gears",
  "flow-data": "fa-solid fa-table",
  "flow-document": "fa-solid fa-file-lines",
  algorithm: "fa-solid fa-brain",
  "algorithm-condition": "fa-solid fa-code-branch",
  "algorithm-loop": "fa-solid fa-repeat",
  "algorithm-recursion": "fa-solid fa-rotate-left",
  "algorithm-sort": "fa-solid fa-arrow-down-short-wide",
  "algorithm-search": "fa-solid fa-magnifying-glass",
  "algorithm-graph": "fa-solid fa-diagram-project",
  "algorithm-tree": "fa-solid fa-tree",
  "algorithm-hash-table": "fa-solid fa-table-cells",
  "algorithm-stack": "fa-solid fa-layer-group",
  "algorithm-queue": "fa-solid fa-list-ol",
  "algorithm-linked-list": "fa-solid fa-link"
};

export const getNodeIconLabel = (kind: ArchitectureNodeKind): string =>
  iconLabels[kind] ?? "NODE";

export const getNodeIconClass = (kind: ArchitectureNodeKind): string =>
  iconClasses[kind] ?? "fa-solid fa-circle-nodes";
